version: '3.9'

services:
  qc_mysql:
    image: mysql:8.0.31
    container_name: qc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  qc_postgres:
    image: postgres:14.8-alpine3.18
    container_name: qc_postgres
    environment:
      POSTGRES_DB:  test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
  qc_redis:
    image: redis:latest
    container_name: qc_redis
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mysql_data:
  postgres_data:
  redis_data:
